### ISSUE TITLE
Better documentation please?

### ISSUE THREAD

**Issue by kevinrue** [taleinat/fuzzysearch#1]
I very much appreciate the effort of coding this package.
However, rather than spending hours guessing from the code, I wish there was a minimal explanation of the difference between find_near_matches and find_near_matches_with_ngrams.

I wanted to post this as a comment somewhere, but I couldn't find where. However, it works well as an issue too!

Many thanks!

**Comment by taleinat** [comment]
For the record, `fuzzysearch` now allows settings specific limits on the number of allowed insertions, deletions and/or substitutions, in addition to the maximum Levenshtein distance. It also uses various optimizations in suitable scenarios, e.g. when only substitutions are allowed.

I'm still leaving this open since the documentation still needs to be improved.

**Comment by taleinat** [comment]
Closing as the documentation has been improved to the point where the original request has been addressed.
